import { jsPDF } from 'jspdf';
import { Invoice, Expense } from '../types';
import { formatCurrency, formatDate } from '../lib/utils';

export const generateInvoicePDF = async (invoice: Invoice): Promise<void> => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(59, 130, 246); // Primary blue
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 20, 25);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.invoiceNumber, pageWidth - 20, 25, { align: 'right' });

  // Reset text color
  doc.setTextColor(0, 0, 0);

  // Invoice Info Section
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Invoice Date:', 20, 55);
  doc.text('Due Date:', 20, 62);
  doc.text('Status:', 20, 69);

  doc.setFont('helvetica', 'normal');
  doc.text(formatDate(invoice.issueDate), 60, 55);
  doc.text(formatDate(invoice.dueDate), 60, 62);

  // Status badge color
  const statusColor =
    invoice.status === 'paid'
      ? [16, 185, 129]
      : invoice.status === 'pending'
        ? [245, 158, 11]
        : invoice.status === 'overdue'
          ? [239, 68, 68]
          : [156, 163, 175];
  doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
  doc.text(invoice.status.toUpperCase(), 60, 69);
  doc.setTextColor(0, 0, 0);

  // Bill To Section
  doc.setFillColor(249, 250, 251);
  doc.rect(pageWidth - 90, 50, 70, 30, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('BILL TO', pageWidth - 85, 57);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(invoice.clientName, pageWidth - 85, 65);
  doc.text(invoice.email, pageWidth - 85, 72);

  // Line Items Table
  const tableTop = 95;
  const colWidths = [80, 25, 35, 35];
  const colX = [20, 100, 125, 160];

  // Table Header
  doc.setFillColor(243, 244, 246);
  doc.rect(15, tableTop - 7, pageWidth - 30, 10, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('Description', colX[0], tableTop);
  doc.text('Qty', colX[1], tableTop);
  doc.text('Price', colX[2], tableTop);
  doc.text('Total', colX[3], tableTop);

  // Table Rows
  doc.setFont('helvetica', 'normal');
  let currentY = tableTop + 12;

  invoice.items.forEach((item, index) => {
    doc.text(item.description.substring(0, 40), colX[0], currentY);
    doc.text(item.quantity.toString(), colX[1], currentY);
    doc.text(formatCurrency(item.unitPrice), colX[2], currentY);
    doc.text(formatCurrency(item.total), colX[3], currentY);

    // Row separator
    doc.setDrawColor(229, 231, 235);
    doc.line(15, currentY + 4, pageWidth - 15, currentY + 4);

    currentY += 12;
  });

  // Totals Section
  const totalsY = currentY + 15;
  doc.setFillColor(249, 250, 251);
  doc.rect(pageWidth - 90, totalsY - 5, 70, 45, 'F');

  doc.setFontSize(9);
  doc.text('Subtotal:', pageWidth - 85, totalsY + 5);
  doc.text(formatCurrency(invoice.subtotal), pageWidth - 25, totalsY + 5, { align: 'right' });

  doc.text('Tax (19%):', pageWidth - 85, totalsY + 15);
  doc.text(formatCurrency(invoice.taxAmount), pageWidth - 25, totalsY + 15, { align: 'right' });

  doc.setDrawColor(59, 130, 246);
  doc.line(pageWidth - 85, totalsY + 22, pageWidth - 25, totalsY + 22);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('TOTAL:', pageWidth - 85, totalsY + 33);
  doc.setTextColor(59, 130, 246);
  doc.text(formatCurrency(invoice.amount), pageWidth - 25, totalsY + 33, { align: 'right' });

  // Footer
  doc.setTextColor(156, 163, 175);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(
    'Generated by Nova Invoice AI - Tunisian Data Sovereignty Compliant',
    pageWidth / 2,
    280,
    { align: 'center' }
  );
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, 285, {
    align: 'center',
  });

  // Save the PDF
  doc.save(`${invoice.invoiceNumber}.pdf`);
};

export const generateExpenseReport = async (
  expenses: Expense[],
  title: string = 'Expense Report'
): Promise<void> => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(16, 185, 129); // Emerald
  doc.rect(0, 0, pageWidth, 35, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 20, 23);

  doc.setTextColor(0, 0, 0);

  // Summary
  const totalAmount = expenses.reduce((sum, e) => sum + e.amount, 0);
  const approvedAmount = expenses
    .filter((e) => e.status === 'approved')
    .reduce((sum, e) => sum + e.amount, 0);

  doc.setFontSize(10);
  doc.text(`Total Expenses: ${formatCurrency(totalAmount)}`, 20, 50);
  doc.text(`Approved: ${formatCurrency(approvedAmount)}`, 20, 58);
  doc.text(`Report Date: ${new Date().toLocaleDateString()}`, pageWidth - 20, 50, {
    align: 'right',
  });

  // Table
  const tableTop = 75;
  const colX = [20, 55, 95, 135, 165];

  // Table Header
  doc.setFillColor(243, 244, 246);
  doc.rect(15, tableTop - 7, pageWidth - 30, 10, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.text('Date', colX[0], tableTop);
  doc.text('Category', colX[1], tableTop);
  doc.text('Vendor', colX[2], tableTop);
  doc.text('Amount', colX[3], tableTop);
  doc.text('Status', colX[4], tableTop);

  // Table Rows
  doc.setFont('helvetica', 'normal');
  let currentY = tableTop + 10;

  expenses.forEach((expense) => {
    if (currentY > 270) {
      doc.addPage();
      currentY = 20;
    }

    doc.text(formatDate(expense.expenseDate), colX[0], currentY);
    doc.text(expense.category.substring(0, 12), colX[1], currentY);
    doc.text(expense.vendorName.substring(0, 15), colX[2], currentY);
    doc.text(formatCurrency(expense.amount), colX[3], currentY);
    doc.text(expense.status.toUpperCase(), colX[4], currentY);

    doc.setDrawColor(229, 231, 235);
    doc.line(15, currentY + 3, pageWidth - 15, currentY + 3);

    currentY += 10;
  });

  doc.save(`expense-report-${Date.now()}.pdf`);
};

export const exportToCSV = (data: any[], filename: string): void => {
  if (data.length === 0) return;

  const headers = Object.keys(data[0]);
  const csvContent = [
    headers.join(','),
    ...data.map((row) =>
      headers
        .map((header) => {
          const value = row[header];
          // Escape commas and quotes in values
          if (typeof value === 'string' && (value.includes(',') || value.includes('"'))) {
            return `"${value.replace(/"/g, '""')}"`;
          }
          return value;
        })
        .join(',')
    ),
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${filename}.csv`;
  link.click();
  URL.revokeObjectURL(link.href);
};

export const exportInvoicesToCSV = (invoices: Invoice[]): void => {
  const data = invoices.map((inv) => ({
    'Invoice Number': inv.invoiceNumber,
    Client: inv.clientName,
    Email: inv.email,
    Amount: inv.amount,
    Status: inv.status,
    'Invoice Date': inv.issueDate,
    'Due Date': inv.dueDate,
    Subtotal: inv.subtotal,
    Tax: inv.taxAmount,
  }));

  exportToCSV(data, `invoices-${Date.now()}`);
};

export const exportExpensesToCSV = (expenses: Expense[]): void => {
  const data = expenses.map((exp) => ({
    Date: exp.expenseDate,
    Category: exp.category,
    Vendor: exp.vendorName,
    Description: exp.description,
    Amount: exp.amount,
    Status: exp.status,
  }));

  exportToCSV(data, `expenses-${Date.now()}`);
};
